### ISSUE TITLE
Quaver Bot Made from MemoryLib confusion

### ISSUE THREAD

**Issue by CassyG** [Sandwich-Group/MemoryLib#7]
So, I couldn't contact the original user because they archived the thing. It's called crochet and it's a quaver bot made with a modified version of memory lib, I have no idea how to run it and I'm very very confused, I haven't done much coding before and I want to learn how so I can run this thing.
![2021-06-21 (1)](https://user-images.githubusercontent.com/76430978/122857076-c5e1c100-d2cc-11eb-871f-1f5a35d8397f.png)
![2021-06-21](https://user-images.githubusercontent.com/76430978/122857089-ca0dde80-d2cc-11eb-9c2d-e1aaa37007a6.png)

**Comment by holly-hacker** [comment]
this is not the repository for crotchet. if they archived the repo, they are most likely not willing to support it and i have no experience with it.

cc @Azukee
